<div class=" offers-details-section mb-5 flex flex-col justify-center hidden">
    <div class="inline-om grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div class="m-auto w-full text-light p-4">
            <h3 class="module-heading font-bold mb-4">Our communities, <br> our commitment.</h3>
            <p class="module-text">Our marketplace promotes efficient use of existing parking spaces as well as a more
                environmentally sustainable way of using our roads. Our partnership with local businesses and councils
                demonstrates how our technology is also helping towns and cities become safer, more efficient, and more
                beautiful.</p>
        </div>

        <img id="img-detail" src="<?= get_template_directory_uri(); ?>/assets/images/offers-menu.png">
    </div>

    <!-- Offers details section -->
    <section class="mx-20 mt-4 text-center grid grid-cols-1 lg:grid-cols-3 gap-4 lg:gap-24 xl:gap-28">

        <div class="offer-details" id="offer1">
            <h3 class="medium-text font-bold"> +75,000 total hours saved</h3>
            <p class="tagline">+75,000 hours saved looking for parking by finding a space through
                PrishtinaParking.</p>
        </div>
        <div class="offer-details" id="offer2">
            <h3 class="medium-text font-bold">+355t CO2 emissions saved</h3>
            <p class="tagline">+355t tons of CO2 emissions saved by booking a space and driving straight
                to the location.</p>
        </div>
        <div class="offer-details" id="offer3">
            <h3 class="medium-text font-bold">+54,000 trees planted to-date</h3>
            <p class="tagline">+54,000 trees planted to-date, offsetting the carbon generated by 4.8
                million miles of driving.</p>
        </div>
    </section>

    <button class="show-less-btn mt-4 mx-auto bg-menublue text-base">Show less</button>
</div>