<!-- Offers menu container section -->
<div class="offers-menu-section mx-20 flex flex-col justify-center my-5">
    <h3 class="module-heading font-bold text-center">
        A greener way to travel
    </h3>
    <div class="thick-underline"></div>
    <div class="grid text-center grid-cols-1 lg:grid-cols-3 gap-10 lg:gap-24 xl:gap-28">
        <!-- Offer cards -->
        <div class="card-om bg-gray-300 ">

            <h4 class="medium-text font-bold mb-2">+75,000 total hours saved in total</h4>
            <p class="tagline">+75,000 hours saved looking for parking by finding a space through PrishtinaParking.
            </p>

        </div>
        <div class="card-om  bg-gray-300">

            <h4 class="medium-text font-bold mb-2">+355t CO2 emissions saved currently</h4>
            <p class="tagline">+355t tons of CO2 emissions saved by booking a space and driving straight to the
                location.</p>
        </div>

        <div class="card-om bg-gray-300">

            <h4 class="medium-text font-bold mb-2">+54,000 trees planted to-date</h4>
            <p class="tagline">+54,000 trees planted to-date, offsetting the carbon generated by 4.8 million miles of
                driving.</p>

        </div>
    </div>
    <button class="expand-btn mx-auto bg-menublue mt-4 text-base">Find out more</button>
</div>